"""Generate ``MODEL_CARD.md`` from training metadata (``metrics.json``).

The card is regenerated by every ``python -m ml.train`` run; do not edit it by hand. Every
number it prints sits under the evaluation label recorded at training time — for the synthetic
dataset, "synthetic hold-out evaluation - not real-world performance".

CLI: ``python -m ml.model_card [--metrics PATH] [--out PATH]``.
"""

from __future__ import annotations

import argparse
import json
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any

from ml.evaluate import SYNTHETIC_LABEL

DEFAULT_DIR = Path(__file__).resolve().parent.parent / "app" / "analysis" / "artifacts"


def _fmt(value: Any) -> str:
    if value is None:
        return "n/a"
    if isinstance(value, bool):
        return "yes" if value else "no"
    if isinstance(value, float):
        return f"{value:.4f}"
    return str(value).replace("|", "\\|").replace("\n", " ")


def _table(headers: Sequence[str], rows: Sequence[Sequence[Any]]) -> list[str]:
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    lines += ["| " + " | ".join(_fmt(cell) for cell in row) + " |" for row in rows]
    return lines


def _get(meta: Mapping[str, Any], *keys: str) -> Any:
    value: Any = meta
    for key in keys:
        value = value.get(key) if isinstance(value, Mapping) else None
    return value


def render_model_card(meta: Mapping[str, Any]) -> str:
    evaluation = _get(meta, "evaluation") or {}
    label = str(evaluation.get("label") or SYNTHETIC_LABEL)
    caption = f"_Every number in this table: {label}._"
    dataset = _get(meta, "dataset") or {}
    libraries = _get(meta, "libraries") or {}
    synthetic = bool(dataset.get("synthetic", True))

    out: list[str] = ["# Warden behaviour model - model card", ""]
    if synthetic:
        out += [
            f"> **SYNTHETIC EVALUATION.** Every number in this card is a {label}. The training and hold-out",
            "> rows are sampled from hand-written distributions in `ml/generate_dataset.py`; no real package",
            "> corpus was used, so none of these figures predicts how the model performs on real packages.",
            "",
        ]
    out += ["Generated by `python -m ml.train`. Do not edit by hand.", "", "## Model details", ""]
    out += _table(["Field", "Value"], [
        ["Model version", f"`{meta.get('model_version')}`"],
        ["Artifact sha256", f"`{meta.get('artifact_sha256')}`"],
        ["Trained at", meta.get("trained_at")],
        ["Algorithm", meta.get("algorithm")],
        ["Feature set", f"v{meta.get('feature_set_version')} ({len(meta.get('feature_order') or [])} features)"],
        ["Feature schema hash", f"`{meta.get('feature_schema_hash')}`"],
        ["Libraries", ", ".join(f"{k} {v}" for k, v in sorted(libraries.items()))],
    ])
    semantics = _get(meta, "score_semantics") or {}
    out += [
        "", "## Intended use", "",
        "- Supplies a supporting malicious-behaviour probability that the scorer fuses with the transparent rule",
        "  score as `max(rule, ml)`: the model can raise a verdict but never lower a deterministic one.",
        "- Not a standalone verdict and not a vulnerability score: vulnerability findings are not model features.",
        "", "## Scores served", "",
    ]
    out += [f"- `{name}`: {text}" for name, text in sorted(semantics.items())]
    out += ["", "## Training data", ""]
    out += _table(["Field", "Value"], [
        ["Dataset", dataset.get("name")],
        ["Dataset version", dataset.get("version")],
        ["Synthetic", dataset.get("synthetic")],
        ["Seed", dataset.get("seed")],
        ["Samples", dataset.get("n")],
        ["Malicious share requested", dataset.get("malicious_ratio")],
        ["Generator hash", f"`{dataset.get('generator_hash')}`" if dataset.get("generator_hash") else None],
    ])
    families = dataset.get("families") if isinstance(dataset.get("families"), Mapping) else {}
    for kind in ("malicious", "benign", "hard_negative"):
        names = families.get(kind) or []
        if names:
            out.append(f"\n{kind.replace('_', ' ').capitalize()} families: " + ", ".join(f"`{n}`" for n in names))

    split = _get(meta, "split") or {}
    out += ["", f"## Evaluation ({label})", "",
            f"Stratified hold-out: {split.get('test_n')} of {dataset.get('n')} samples "
            f"(train {split.get('train_n')}), decision threshold {evaluation.get('threshold')}.", ""]
    metrics = evaluation.get("metrics") or {}
    out += _table(["Metric", "Value", "Evaluation scope"],
                  [[name, metrics.get(name), label] for name in (
                      "accuracy", "precision", "recall", "f1", "roc_auc", "pr_auc", "brier_score",
                      "false_positive_rate", "specificity")])

    cm = evaluation.get("confusion_matrix") or {}
    out += ["", "### Confusion matrix", "", caption, ""]
    out += _table(["", "predicted benign", "predicted malicious"], [
        ["actual benign", cm.get("tn"), cm.get("fp")],
        ["actual malicious", cm.get("fn"), cm.get("tp")],
    ])

    out += ["", "### Threshold table", "", caption, ""]
    out += _table(["Threshold", "Precision", "Recall", "F1", "False-positive rate", "TP", "FP", "TN", "FN"], [
        [row.get("threshold"), row.get("precision"), row.get("recall"), row.get("f1"), row.get("false_positive_rate"),
         row.get("tp"), row.get("fp"), row.get("tn"), row.get("fn")]
        for row in evaluation.get("threshold_table") or []
    ])

    calibration = evaluation.get("calibration") or {}
    out += ["", "### Calibration (reliability bins)", "", caption,
            f"Expected calibration error: {_fmt(calibration.get('expected_calibration_error'))} ({label}).", ""]
    out += _table(["Bin", "Count", "Mean predicted", "Fraction malicious"], [
        [f"{b.get('lower')}-{b.get('upper')}", b.get("count"), b.get("mean_predicted"), b.get("fraction_positive")]
        for b in calibration.get("bins") or []
    ])

    per_group = evaluation.get("per_group") or {}
    if per_group:
        out += ["", "### Per family", "", caption,
                "Detection rate for malicious families; false-positive rate for benign families.", ""]
        out += _table(["Family", "Label", "Samples", "Rate", "Rate type", "Mean probability"], [
            [name, row.get("label"), row.get("n"), row.get("flagged_rate"), row.get("metric"),
             row.get("mean_probability")]
            for name, row in sorted(per_group.items(), key=lambda kv: (-(kv[1].get("label") or 0), kv[0]))
        ])

    importances = _get(meta, "feature_importances") or {}
    impurity = importances.get("impurity") or {}
    permutation = importances.get("permutation") or {}
    out += ["", "### Feature importances", "", caption,
            f"Impurity importance (mean over the calibrated ensemble's base forests) and permutation importance "
            f"({importances.get('permutation_scoring')} drop on the hold-out set, "
            f"{importances.get('permutation_repeats')} repeats).", ""]
    out += _table(["Feature", "Impurity", "Permutation mean", "Permutation std"], [
        [name, impurity.get(name), (permutation.get(name) or {}).get("mean"), (permutation.get(name) or {}).get("std")]
        for name in sorted(impurity, key=lambda n: (-(impurity.get(n) or 0.0), n))
    ])

    out += [
        "", "## Limitations", "",
        "- Synthetic data: the archetypes encode assumptions about what attacks and hard negatives look like in",
        "  Warden's feature space. Real attacks that do not match them, and benign packages unlike the hard",
        "  negatives, are not represented; real-world precision and recall are unknown.",
        "- Calibration is measured at the synthetic class balance; production base rates differ, so probabilities",
        "  are not calibrated for real traffic.",
        "- An attacker who knows the feature set can try to avoid the features the model relies on. This is why",
        "  the model only supplements rules, IOC matching and policy.",
        "- Features are only as good as the analyzers behind them: a detector miss is a zero feature.",
        "- Drift (`GET /ml/drift`) compares recent scans with this training data; drift shows that inputs differ",
        "  from the synthetic training distribution, not that an attack happened.",
        "",
    ]
    return "\n".join(out)


def write_model_card(meta: Mapping[str, Any], path: Path) -> Path:
    path = Path(path)
    path.write_text(render_model_card(meta), encoding="utf-8", newline="\n")
    return path


def main(argv: Sequence[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Regenerate MODEL_CARD.md from metrics.json.")
    ap.add_argument("--metrics", type=Path, default=DEFAULT_DIR / "metrics.json")
    ap.add_argument("--out", type=Path, default=DEFAULT_DIR / "MODEL_CARD.md")
    args = ap.parse_args(argv)
    meta = json.loads(args.metrics.read_text(encoding="utf-8"))
    print(f"Wrote {write_model_card(meta, args.out)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
