"""Local CLI commands that run Warden's engines in-process (no API server needed).

These commands need the server extras (``pip install "warden-supply-chain-firewall[server]"``);
the API-backed ``scan`` and ``gate`` commands keep working with the lightweight base install, so
every engine import here is deferred until a local command actually runs.

Nothing here executes project code or contacts the network: manifests are read from disk with the
same bounded, link-refusing discovery the server uses, and every attacker-influenced string is
passed through ``terminal_safe`` before it reaches the terminal.

Exit codes follow the CLI convention: ``0`` success, ``2`` the check failed (invalid policy,
blocking project findings), ``3`` usage or environment error.
"""

from __future__ import annotations

import json
import os
import sys
from collections.abc import Callable
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

EXIT_OK = 0
EXIT_FAILED = 2
EXIT_USAGE = 3

_SEVERITY_ORDER = {"info": 0, "low": 1, "medium": 2, "high": 3, "critical": 4}


class EngineUnavailable(RuntimeError):
    """The analysis engine is not installed (base CLI install)."""


def _require_engine() -> None:
    try:
        import app.sbom  # noqa: F401
    except ImportError as exc:  # pragma: no cover - depends on the installation
        raise EngineUnavailable(
            'local commands need the analysis engine: pip install "warden-supply-chain-firewall[server]"'
        ) from exc


def _safe(value: object) -> str:
    from app.core.redaction import terminal_safe

    return terminal_safe(value)


def _reproducible_timestamp() -> datetime:
    """Honour SOURCE_DATE_EPOCH so SBOMs can be regenerated byte-for-byte."""
    epoch = os.environ.get("SOURCE_DATE_EPOCH", "").strip()
    if epoch.isdigit():
        return datetime.fromtimestamp(int(epoch), tz=timezone.utc)
    return datetime.now(timezone.utc).replace(microsecond=0)


def _write_or_print(payload: str, output: str | None) -> None:
    if output:
        Path(output).write_text(payload, encoding="utf-8")
        print(f"wrote {output}", file=sys.stderr)
    else:
        print(payload)


def load_inventory(path: str, project_name: str | None = None) -> tuple[Any, list[str]]:
    """Discover and parse the manifests under ``path``; returns (inventory, discovery warnings)."""
    _require_engine()
    from app.sbom import discover_manifests, parse_project

    root = Path(path)
    if not root.is_dir():
        raise FileNotFoundError(f"not a directory: {path}")
    notes: list[str] = []
    files = discover_manifests(root, warnings=notes)
    name = project_name or root.resolve().name or "project"
    return parse_project(files, name), notes


# --------------------------------------------------------------------------- sbom generate
def cmd_sbom_generate(args: Any) -> int:
    try:
        inventory, notes = load_inventory(args.path, args.project_name)
    except (EngineUnavailable, FileNotFoundError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return EXIT_USAGE
    if not inventory.manifests:
        print(f"error: no supported manifests found under {_safe(args.path)}", file=sys.stderr)
        return EXIT_USAGE

    from app import __version__
    from app.sbom import build_cyclonedx, build_spdx

    builder: Callable[..., dict] = build_cyclonedx if args.format == "cyclonedx" else build_spdx
    document = builder(inventory, timestamp=_reproducible_timestamp(), tool_version=__version__)
    _write_or_print(json.dumps(document, indent=2, sort_keys=True), args.output)
    for warning in [*notes, *inventory.warnings][:20]:
        print(f"warning: {_safe(warning)}", file=sys.stderr)
    print(f"{len(inventory.components)} component(s) from {len(inventory.manifests)} manifest(s)", file=sys.stderr)
    return EXIT_OK


# --------------------------------------------------------------------------- policy validate
def cmd_policy_validate(args: Any) -> int:
    try:
        _require_engine()
    except EngineUnavailable as exc:
        print(f"error: {exc}", file=sys.stderr)
        return EXIT_USAGE
    from app.policy.document import validate_policy_text

    path = Path(args.file)
    try:
        text = path.read_bytes()
    except OSError as exc:
        print(f"error: cannot read {_safe(args.file)}: {type(exc).__name__}", file=sys.stderr)
        return EXIT_USAGE
    fmt = "json" if path.suffix.lower() == ".json" else "yaml"
    outcome = validate_policy_text(text, fmt)

    if args.format == "json":
        print(json.dumps({
            "valid": outcome.valid,
            "errors": list(outcome.errors),
            "warnings": list(outcome.warnings),
            "policy_hash": outcome.policy_hash,
        }, indent=2, default=str))
    elif outcome.valid:
        print(f"valid  {_safe(path.name)}  policy_hash={outcome.policy_hash}")
        for warning in outcome.warnings:
            print(f"  warning: {_safe(_describe(warning))}")
    else:
        print(f"INVALID  {_safe(path.name)}", file=sys.stderr)
        for error in outcome.errors:
            print(f"  {_safe(_describe(error))}", file=sys.stderr)
    return EXIT_OK if outcome.valid else EXIT_FAILED


def _describe(item: object) -> str:
    if isinstance(item, dict):
        loc = item.get("loc")
        where = ".".join(str(p) for p in loc) if isinstance(loc, (list, tuple)) else str(loc or "")
        message = item.get("msg") or item.get("message") or ""
        return f"{where}: {message}" if where else str(message)
    return str(item)


# --------------------------------------------------------------------------- project scan
def cmd_project_scan(args: Any) -> int:
    try:
        inventory, notes = load_inventory(args.path, args.project_name)
    except (EngineUnavailable, FileNotFoundError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return EXIT_USAGE
    if not inventory.manifests:
        print(f"error: no supported manifests found under {_safe(args.path)}", file=sys.stderr)
        return EXIT_USAGE

    from app.analysis.depconf.project import project_confusion_findings
    from app.graph.engine import build_graph
    from app.sbom import hygiene_findings

    findings = [*hygiene_findings(inventory), *project_confusion_findings(inventory)]
    graph = build_graph(inventory).to_dict()
    metrics = graph.get("metrics", {})
    threshold = _SEVERITY_ORDER[args.fail_on]
    blocking = [f for f in findings if f.severity.rank >= threshold]

    if args.format == "sarif":
        from app import __version__
        from app.reporting.sarif import build_sarif

        log = build_sarif(findings, tool_version=__version__, automation_id=f"warden/project/{inventory.project_name}")
        _write_or_print(json.dumps(log, indent=2), getattr(args, "output", None))
    elif args.format == "json":
        print(json.dumps({
            "project": inventory.project_name,
            "manifests": inventory.manifests,
            "components": len(inventory.components),
            "direct": len(inventory.direct_components()),
            "graph": metrics,
            "findings": [f.to_dict() for f in findings],
            "warnings": [*notes, *inventory.warnings],
            "failed": bool(blocking),
        }, indent=2, default=str))
    else:
        _print_project_table(inventory, findings, metrics, notes)
        if blocking:
            print(f"\nProject check FAILED (fail-on={args.fail_on}): {len(blocking)} finding(s)", file=sys.stderr)
        else:
            print("\nProject check passed.")
    return EXIT_FAILED if blocking else EXIT_OK


def _print_project_table(inventory: Any, findings: list, metrics: dict, notes: list[str]) -> None:
    print(f"WARDEN PROJECT SCAN  {_safe(inventory.project_name)}")
    print("-" * 60)
    manifest_names = ", ".join(_safe(m.get("file", "?")) for m in inventory.manifests)
    print(f"Manifests     {manifest_names}")
    print(f"Components    {len(inventory.components)} ({len(inventory.direct_components())} direct)")
    print(f"Max depth     {metrics.get('max_depth', '-')}")
    single_points = metrics.get("single_points") or []
    if single_points:
        names = ", ".join(_safe(p.get("name") or p.get("id")) for p in single_points[:5])
        print(f"Single points {names}")
    print()
    if not findings:
        print("No dependency-hygiene or dependency-confusion findings.")
    for finding in sorted(findings, key=lambda f: (-f.severity.rank, f.code)):
        loc = finding.location
        where = f"{loc.file}:{loc.line}" if loc and loc.file and loc.line else (loc.file if loc and loc.file else "")
        print(f"{finding.severity.value.upper():8} {finding.code:24} {_safe(where):30} {_safe(finding.message)}")
    for warning in [*notes, *inventory.warnings][:10]:
        print(f"warning: {_safe(warning)}", file=sys.stderr)
