"""Local CLI commands that run Warden's engines in-process (no API server needed).

These commands need the server extras (``pip install "warden-supply-chain-firewall[server]"``);
the API-backed ``scan`` and ``gate`` commands keep working with the lightweight base install, so
every engine import here is deferred until a local command actually runs.

Nothing here executes project code or contacts the network: manifests are read from disk with the
same bounded, link-refusing discovery the server uses, and every attacker-influenced string is
passed through ``terminal_safe`` before it reaches the terminal.

Exit codes follow the CLI convention: ``0`` success, ``2`` the check failed (invalid policy,
blocking project findings), ``3`` usage or environment error.
"""

from __future__ import annotations

import json
import os
import sys
from collections.abc import Callable
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

EXIT_OK = 0
EXIT_FAILED = 2
EXIT_USAGE = 3

_SEVERITY_ORDER = {"info": 0, "low": 1, "medium": 2, "high": 3, "critical": 4}


class EngineUnavailable(RuntimeError):
    """The analysis engine is not installed (base CLI install)."""


def _require_engine() -> None:
    try:
        import app.sbom  # noqa: F401
    except ImportError as exc:  # pragma: no cover - depends on the installation
        raise EngineUnavailable(
            'local commands need the analysis engine: pip install "warden-supply-chain-firewall[server]"'
        ) from exc


def _safe(value: object) -> str:
    from app.core.redaction import terminal_safe

    return terminal_safe(value)


def _reproducible_timestamp() -> datetime:
    """Honour SOURCE_DATE_EPOCH so SBOMs can be regenerated byte-for-byte."""
    epoch = os.environ.get("SOURCE_DATE_EPOCH", "").strip()
    if epoch.isdigit():
        return datetime.fromtimestamp(int(epoch), tz=timezone.utc)
    return datetime.now(timezone.utc).replace(microsecond=0)


def _write_or_print(payload: str, output: str | None) -> None:
    if output:
        Path(output).write_text(payload, encoding="utf-8")
        print(f"wrote {output}", file=sys.stderr)
    else:
        print(payload)


def load_inventory(path: str, project_name: str | None = None) -> tuple[Any, list[str]]:
    """Discover and parse the manifests under ``path``; returns (inventory, discovery warnings)."""
    _require_engine()
    from app.sbom import discover_manifests, parse_project

    root = Path(path)
    if not root.is_dir():
        raise FileNotFoundError(f"not a directory: {path}")
    notes: list[str] = []
    files = discover_manifests(root, warnings=notes)
    name = project_name or root.resolve().name or "project"
    return parse_project(files, name), notes


MAX_CONTAINER_FILES = 50
MAX_CONTAINER_FILE_BYTES = 1_000_000


def container_config_findings(path: str, notes: list[str]) -> list:
    """Lint Dockerfiles and Compose files under ``path`` (bounded walk, links are not followed)."""
    from app.containers.dockerfile import is_compose_file, is_dockerfile, lint_files
    from app.sbom.discover import MAX_SCANNED_ENTRIES, SKIP_DIRS

    root = Path(path)
    files: dict[str, str] = {}
    seen = 0
    for current, dirs, names in os.walk(root, followlinks=False):
        rel_dir = Path(current).relative_to(root)
        dirs[:] = sorted(d for d in dirs if d not in SKIP_DIRS and len(rel_dir.parts) < 4
                         and not os.path.islink(os.path.join(current, d)))
        for name in sorted(names):
            seen += 1
            if seen > MAX_SCANNED_ENTRIES or len(files) >= MAX_CONTAINER_FILES:
                notes.append("container file discovery stopped at its bounds")
                return lint_files(files)
            if not (is_dockerfile(name) or is_compose_file(name)):
                continue
            full = Path(current) / name
            if full.is_symlink() or not full.is_file() or full.stat().st_size > MAX_CONTAINER_FILE_BYTES:
                notes.append(f"skipped container file {_safe((rel_dir / name).as_posix())}")
                continue
            files[(rel_dir / name).as_posix()] = full.read_text(encoding="utf-8", errors="replace")
    return lint_files(files)


# --------------------------------------------------------------------------- sbom generate
def cmd_sbom_generate(args: Any) -> int:
    try:
        inventory, notes = load_inventory(args.path, args.project_name)
    except (EngineUnavailable, FileNotFoundError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return EXIT_USAGE
    if not inventory.manifests:
        print(f"error: no supported manifests found under {_safe(args.path)}", file=sys.stderr)
        return EXIT_USAGE

    from app import __version__
    from app.sbom import build_cyclonedx, build_spdx

    builder: Callable[..., dict] = build_cyclonedx if args.format == "cyclonedx" else build_spdx
    document = builder(inventory, timestamp=_reproducible_timestamp(), tool_version=__version__)
    _write_or_print(json.dumps(document, indent=2, sort_keys=True), args.output)
    for warning in [*notes, *inventory.warnings][:20]:
        print(f"warning: {_safe(warning)}", file=sys.stderr)
    print(f"{len(inventory.components)} component(s) from {len(inventory.manifests)} manifest(s)", file=sys.stderr)
    return EXIT_OK


# --------------------------------------------------------------------------- policy validate
def cmd_policy_validate(args: Any) -> int:
    try:
        _require_engine()
    except EngineUnavailable as exc:
        print(f"error: {exc}", file=sys.stderr)
        return EXIT_USAGE
    from app.policy.document import validate_policy_text

    path = Path(args.file)
    try:
        text = path.read_bytes()
    except OSError as exc:
        print(f"error: cannot read {_safe(args.file)}: {type(exc).__name__}", file=sys.stderr)
        return EXIT_USAGE
    fmt = "json" if path.suffix.lower() == ".json" else "yaml"
    outcome = validate_policy_text(text, fmt)

    if args.format == "json":
        print(json.dumps({
            "valid": outcome.valid,
            "errors": list(outcome.errors),
            "warnings": list(outcome.warnings),
            "policy_hash": outcome.policy_hash,
        }, indent=2, default=str))
    elif outcome.valid:
        print(f"valid  {_safe(path.name)}  policy_hash={outcome.policy_hash}")
        for warning in outcome.warnings:
            print(f"  warning: {_safe(_describe(warning))}")
    else:
        print(f"INVALID  {_safe(path.name)}", file=sys.stderr)
        for error in outcome.errors:
            print(f"  {_safe(_describe(error))}", file=sys.stderr)
    return EXIT_OK if outcome.valid else EXIT_FAILED


def _describe(item: object) -> str:
    if isinstance(item, dict):
        loc = item.get("loc")
        where = ".".join(str(p) for p in loc) if isinstance(loc, (list, tuple)) else str(loc or "")
        message = item.get("msg") or item.get("message") or ""
        return f"{where}: {message}" if where else str(message)
    return str(item)


# --------------------------------------------------------------------------- project scan
def cmd_project_scan(args: Any) -> int:
    try:
        inventory, notes = load_inventory(args.path, args.project_name)
    except (EngineUnavailable, FileNotFoundError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return EXIT_USAGE
    if not inventory.manifests:
        print(f"error: no supported manifests found under {_safe(args.path)}", file=sys.stderr)
        return EXIT_USAGE

    from app.analysis.depconf.project import project_confusion_findings
    from app.graph.engine import build_graph
    from app.sbom import hygiene_findings

    findings = [*hygiene_findings(inventory), *project_confusion_findings(inventory),
                *container_config_findings(args.path, notes)]
    graph = build_graph(inventory).to_dict()
    metrics = graph.get("metrics", {})
    threshold = _SEVERITY_ORDER[args.fail_on]
    blocking = [f for f in findings if f.severity.rank >= threshold]

    if args.format == "sarif":
        from app import __version__
        from app.reporting.sarif import build_sarif

        log = build_sarif(findings, tool_version=__version__, automation_id=f"warden/project/{inventory.project_name}")
        _write_or_print(json.dumps(log, indent=2), getattr(args, "output", None))
    elif args.format == "json":
        print(json.dumps({
            "project": inventory.project_name,
            "manifests": inventory.manifests,
            "components": len(inventory.components),
            "direct": len(inventory.direct_components()),
            "graph": metrics,
            "findings": [f.to_dict() for f in findings],
            "warnings": [*notes, *inventory.warnings],
            "failed": bool(blocking),
        }, indent=2, default=str))
    else:
        _print_project_table(inventory, findings, metrics, notes)
        if blocking:
            print(f"\nProject check FAILED (fail-on={args.fail_on}): {len(blocking)} finding(s)", file=sys.stderr)
        else:
            print("\nProject check passed.")
    return EXIT_FAILED if blocking else EXIT_OK


def _print_project_table(inventory: Any, findings: list, metrics: dict, notes: list[str]) -> None:
    print(f"WARDEN PROJECT SCAN  {_safe(inventory.project_name)}")
    print("-" * 60)
    manifest_names = ", ".join(_safe(m.get("file", "?")) for m in inventory.manifests)
    print(f"Manifests     {manifest_names}")
    print(f"Components    {len(inventory.components)} ({len(inventory.direct_components())} direct)")
    print(f"Max depth     {metrics.get('max_depth', '-')}")
    single_points = metrics.get("single_points") or []
    if single_points:
        names = ", ".join(_safe(p.get("name") or p.get("id")) for p in single_points[:5])
        print(f"Single points {names}")
    print()
    if not findings:
        print("No dependency-hygiene or dependency-confusion findings.")
    for finding in sorted(findings, key=lambda f: (-f.severity.rank, f.code)):
        loc = finding.location
        where = f"{loc.file}:{loc.line}" if loc and loc.file and loc.line else (loc.file if loc and loc.file else "")
        print(f"{finding.severity.value.upper():8} {finding.code:24} {_safe(where):30} {_safe(finding.message)}")
    for warning in [*notes, *inventory.warnings][:10]:
        print(f"warning: {_safe(warning)}", file=sys.stderr)


# --------------------------------------------------------------------------- diff
def _default_orchestrator() -> Any:
    from app.analysis.orchestrator import Orchestrator

    return Orchestrator()


# Replaced in tests; the real orchestrator downloads both releases from the registry.
orchestrator_factory: Callable[[], Any] = _default_orchestrator


def cmd_diff(args: Any) -> int:
    try:
        _require_engine()
    except EngineUnavailable as exc:
        print(f"error: {exc}", file=sys.stderr)
        return EXIT_USAGE
    from pydantic import ValidationError

    from app.analysis.diff import diff_results
    from app.schemas.diff import DiffRequest

    try:
        request = DiffRequest(name=args.package, from_version=args.from_version, to_version=args.to_version)
    except ValidationError as exc:
        print(f"error: {_safe(exc.errors()[0].get('msg', 'invalid request'))}", file=sys.stderr)
        return EXIT_USAGE

    orchestrator = orchestrator_factory()
    old = orchestrator.analyze(request.ecosystem, request.name, request.from_version)
    new = orchestrator.analyze(request.ecosystem, request.name, request.to_version)
    diff = diff_results(old, new)

    if args.format == "json":
        print(json.dumps(diff, indent=2, default=str))
    else:
        _print_diff(diff)
    if args.fail_on_drift and diff["verdict"] == "escalated":
        print("\nRelease diff FAILED: behaviour escalated", file=sys.stderr)
        return EXIT_FAILED
    return EXIT_OK


def _print_diff(diff: dict) -> None:
    risk = diff["risk"]
    print(f"WARDEN RELEASE DIFF  {_safe(diff['name'])}  {_safe(diff['from_version'])} -> {_safe(diff['to_version'])}")
    print("-" * 60)
    print(f"Verdict       {diff['verdict'].upper()}")
    print(f"Risk          {risk['from']} ({risk['from_severity']}) -> {risk['to']} ({risk['to_severity']})"
          f"  delta {risk['delta']:+d}")
    for name, change in risk["dimensions"].items():
        print(f"  {name:12} {change['from']} -> {change['to']}")
    caps = diff["capabilities"]
    if caps["added"] or caps["removed"]:
        print(f"Capabilities  +{', +'.join(caps['added']) or '-'}  -{', -'.join(caps['removed']) or '-'}")
    files = diff["files"]
    if files.get("available"):
        print(f"Files         +{files['added_count']} -{files['removed_count']} ~{files['changed_count']}")
        for path in files["install_time_changes"][:10]:
            print(f"  install-time  {_safe(path)}")
        for path in files["new_executable_binaries"][:10]:
            print(f"  new binary    {_safe(path)}")
    else:
        print(f"Files         unavailable ({files.get('reason')})")
    maintainers = diff["maintainers"]
    if maintainers.get("added") or maintainers.get("removed"):
        print(f"Maintainers   +{', '.join(map(_safe, maintainers['added'])) or '-'}"
              f"  -{', '.join(map(_safe, maintainers['removed'])) or '-'}")
    for finding in diff["findings"]["added"][:25]:
        where = finding["file"] or ""
        print(f"  NEW {str(finding['severity']).upper():8} {finding['code']:24} {_safe(where):30} "
              f"{_safe(finding['message'])}")
    for finding in diff["findings"]["escalated"][:25]:
        print(f"  UP  {str(finding['severity']).upper():8} {finding['code']:24} was {finding['previous_severity']}")
    for reason in diff["reasons"]:
        print(f"reason: {_safe(reason)}")


# --------------------------------------------------------------------------- image scan
def cmd_image_scan(args: Any) -> int:
    try:
        _require_engine()
    except EngineUnavailable as exc:
        print(f"error: {exc}", file=sys.stderr)
        return EXIT_USAGE
    from app import __version__
    from app.containers.image import MAX_IMAGE_BYTES
    from app.containers.service import scan_image

    archive = Path(args.archive)
    try:
        size = archive.stat().st_size
        if size > MAX_IMAGE_BYTES:
            print(f"error: image archive larger than {MAX_IMAGE_BYTES} bytes", file=sys.stderr)
            return EXIT_USAGE
        data = archive.read_bytes()
    except OSError as exc:
        print(f"error: cannot read {_safe(args.archive)}: {type(exc).__name__}", file=sys.stderr)
        return EXIT_USAGE

    result = scan_image(data, archive.name, vulnerabilities=not args.no_vulnerabilities, offline=args.offline,
                        tool_version=__version__)
    if args.sbom_output:
        Path(args.sbom_output).write_text(json.dumps(result.sbom, indent=2, sort_keys=True), encoding="utf-8")
        print(f"wrote {args.sbom_output}", file=sys.stderr)

    document = {**result.summary(), "vulnerability_scan": result.vulnerability_scan.to_dict(),
                "components": [c.to_dict() for c in result.report.components],
                "findings": [f.to_dict() for f in result.findings]}
    if args.format == "sarif":
        from app.reporting.sarif import build_sarif

        name = result.report.image_refs[0] if result.report.image_refs else archive.name
        _write_or_print(json.dumps(build_sarif(result.findings, tool_version=__version__,
                                               automation_id=f"warden/image/{name}"), indent=2), args.output)
    elif args.format == "json":
        _write_or_print(json.dumps(document, indent=2, default=str), args.output)
    else:
        _print_image_table(document, result.findings)

    threshold = _SEVERITY_ORDER[args.fail_on]
    blocking = [f for f in result.findings if f.severity.rank >= threshold]
    incomplete = not result.report.complete
    if blocking or incomplete:
        why = "image could not be analysed completely" if incomplete and not blocking else \
            f"{len(blocking)} finding(s) at or above {args.fail_on}"
        print(f"\nImage check FAILED: {why}", file=sys.stderr)
        return EXIT_FAILED
    return EXIT_OK


def _print_image_table(document: dict, findings: list) -> None:
    refs = document.get("image_refs") or ["(untagged)"]
    print(f"WARDEN IMAGE SCAN  {_safe(refs[0])}")
    print("-" * 60)
    print(f"Decision      {str(document['decision']).upper()}  (risk {document['risk_score']})")
    print(f"Digest        {_safe(document.get('config_digest') or '-')}")
    print(f"Platform      {_safe(document.get('os') or '-')}/{_safe(document.get('architecture') or '-')}")
    print(f"User          {_safe(document.get('user') or 'root (default)')}")
    counts = document.get("component_counts") or {}
    print(f"Packages      {', '.join(f'{k} {v}' for k, v in sorted(counts.items())) or 'none found'}")
    scan = document["vulnerability_scan"]
    print(f"Vulnerability scan  {scan['status']}" + (f" ({_safe(scan['detail'])})" if scan.get("detail") else ""))
    print(f"Complete      {'yes' if document.get('complete') else 'NO'}")
    print()
    for finding in findings[:100]:
        loc = finding.location.file if finding.location and finding.location.file else ""
        print(f"{finding.severity.value.upper():8} {finding.code:26} {_safe(loc)[:40]:40} {_safe(finding.message)}")
    for reason in document.get("reasons") or []:
        print(f"reason: {_safe(reason)}")


# --------------------------------------------------------------------------- report
def cmd_report(args: Any) -> int:
    try:
        _require_engine()
    except EngineUnavailable as exc:
        print(f"error: {exc}", file=sys.stderr)
        return EXIT_USAGE
    from app import __version__
    from app.reporting.documents import UnsupportedResult, load_result, render_html, render_markdown

    try:
        raw = Path(args.input).read_bytes() if args.input != "-" else sys.stdin.buffer.read()
        if len(raw) > 64 * 1024 * 1024:
            raise ValueError("input larger than 64 MiB")
        loaded = load_result(json.loads(raw.decode("utf-8")))
    except (OSError, ValueError, UnsupportedResult) as exc:
        print(f"error: cannot build a report: {_safe(exc)}", file=sys.stderr)
        return EXIT_USAGE

    if args.format == "sarif":
        from app.reporting.sarif import build_sarif

        payload = json.dumps(build_sarif(loaded.findings, tool_version=__version__,
                                         automation_id=f"warden/{loaded.kind}"), indent=2)
    elif args.format == "html":
        payload = render_html(loaded)
    else:
        payload = render_markdown(loaded)
    _write_or_print(payload, args.output)
    return EXIT_OK
